
# Site settings

# Delete the lines you don't need
# about 5 elements are recomended
github_username:  changhc
#facebook_username: "100000440013230"
linkedin_username: "~hc"
#flickr_username: your_flickr_username_goes_here
blog_url: "./blog/"
cv_url: "./resume.pdf"

# Build settings
markdown: kramdown
permalink: pretty


# NB! Set your site's url, otherwise stuff will break :)

url: "https://changhc.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /

# Google tracking id

google-tracking-id: "UA-76356561-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Huan-Cheng Chang"
title: "{ Huan-Cheng Chang }"
description: "Huan-Cheng Chang's website."
#keywords: "Huan-Cheng, Chang, personal, jekyll"
favicon: "/img/favicon-camera-retro.ico"

################
# Header layout #
################

black-favicon: "/img/favicon-camera-retro-black.ico"

background-img: "../img/pexels-photo-27665-blur.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/me.jpg"

self-intro: "M.S. in Computer Science, École polytechnique fédérale de Lausanne (EPFL)<br>
Aiming to build impactful products and solve real world challenges."

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

#enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

#email-share: True
fb-share: True
twitter-share: True
#linkedin-share: True
#reddit-share: True
#google-plus-share: True
#tumblr-share: True
#pinterest-share: True
pocket-share: True
#vkontakte-share: True

#disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "hello@changhc.me"

############
# 404 page #
############

not-found-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Project: 'project'
  Blog: 'blog-link'
#  Timeline: 'timeline'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-assets
